### PR TITLE
Remove usage of deprecated Asio API

### LINKED ISSUE #970: crow using boost::asio error : "boost::asio has no member io_service"
I use boost_1_87_0 to compile crow web service on windows 10, but failed. 
The error is "namespace boost::asio has no member io_service". 
I have check this error and found this: now boost::asio::io_service has been replaced by boost:asio::io_context.
Hope maintainer update code to support the latest boost::asio version, thank you ^_^

### PR DESCRIPTION
**Pull request by bugdea1er**
Remove all uses of deprecated Asio API, like `asio::io_service` and `asio::ip::address::from_string` (tested with compilation flag `ASIO_NO_DEPRECATED`)

This automatically fixes building with newer versions of Boost

Closes #970

### CODE REVIEW

File: include/crow/socket_adaptors.h [hunk 1]
```diff
@@ -38,11 +38,11 @@ namespace crow
...
     {
         using context = void;
-        SocketAdaptor(asio::io_service& io_service, context*):
-          socket_(io_service)
+        SocketAdaptor(asio::io_context& io_context, context*):
+          socket_(io_context)
         {}
 
-        asio::io_service& get_io_service()
+        asio::io_context& get_io_service()
```
Comment (gittiver) [inline include/crow/socket_adaptors.h:45]: Shouldn't that also be renamed to get_io_context() to be consistent?

File: include/crow/http_server.h [hunk 2]
```diff
@@ -43,9 +43,9 @@ namespace crow // NOTE: Already documented in "crow/app.h"
     {
     public:
         Server(Handler* handler, std::string bindaddr, uint16_t port, std::string server_name = std::string("Crow/") + VERSION, std::tuple<Middlewares...>* middlewares = nullptr, uint16_t concurrency = 1, uint8_t timeout = 5, typename Adaptor::context* adaptor_ctx = nullptr):
-          acceptor_(io_service_, tcp::endpoint(asio::ip::address::from_string(bindaddr), port)),
-          signals_(io_service_),
-          tick_timer_(io_service_),
+          acceptor_(io_context_, tcp::endpoint(asio::ip::make_address(bindaddr), port)),
```
Comment (gittiver) [inline include/crow/http_server.h:46]: I moved the endpoint creation out of the server constructor in  
https://github.com/CrowCpp/Crow/pull/918/files
This change would collide. 
technically seen it is correct but will make merge problems. Just FYI.

**Review by gittiver — CHANGES_REQUESTED** [review]

**Comment by gittiver** [comment]
btw, I fixed the codeQL problem, could you rebase onto master to get this change too.

File: include/crow/socket_adaptors.h (hunk 1 above)
Comment (bugdea1er) [reply include/crow/socket_adaptors.h]: Missed that, this is fixed now

**Comment by bugdea1er** [comment]
> btw, I fixed the codeQL problem, could you rebase onto master to get this change too.

Done!

**Review by gittiver — APPROVED** [review]
