### PR TITLE
Handle unknown static file extensions

### LINKED ISSUE #410: Requesting a static file with an extension crow doens't know about causes an uncaught exception
Asking crow to respond to a static file request using `crow::response::set_static_file_info` causes an uncaught `std::out_of_range` exception if the file's extension is not one crow knows about (i.e. not in `crow::mime_types`).

### PR DESCRIPTION
**Pull request by danielskeenan**
Fixes #410.

### CODE REVIEW

File: include/crow/http_response.h [hunk 1]
```diff
@@ -246,13 +246,17 @@ namespace crow
                 code = 200;
                 this->add_header("Content-length", std::to_string(file_info.statbuf.st_size));
 
-                if (extension != "")
+                if (!extension.empty())
```
Comment (mrozigor) [inline include/crow/http_response.h:249]: If extension is empty then `Content-length` will be set and `Content-Type` not? Also wouldn't it be better to check if extension exists in map to avoid handling exceptions?

Comment (danielskeenan) [reply include/crow/http_response.h:249]: Re `Content-Type` - not sending that header when the file has no extension does match previous behavior (see [here](https://github.com/CrowCpp/Crow/blob/db53bd619b51d4e45c03206adcb38eaf9683562a/include/crow/http_response.h#L249)), but now that I hear you say it that does sound wrong.  Looking at the [HTTP spec](https://datatracker.ietf.org/doc/html/rfc2616#section-7.2.1), it appears that, when a client receives a response missing `Content-Type`, it should introspect the body and guess the content type, or assume `application/octet-stream`.  I suppose we could make that assumption ourselves and send `application/octet-stream` when there's no extension, but this would deny clients that introspection opportunity.  What do you think?

I'll change it to use `find()` instead of exception handling if that's what you prefer.

Comment (mrozigor) [reply include/crow/http_response.h:248]: I guess you're right and we should leave it as it is ;)

File: include/crow/http_response.h [hunk 2]
```diff
@@ -242,17 +242,20 @@ namespace crow
             {
                 std::size_t last_dot = path.find_last_of(".");
                 std::string extension = path.substr(last_dot + 1);
-                std::string mimeType = "";
                 code = 200;
                 this->add_header("Content-length", std::to_string(file_info.statbuf.st_size));
```
Comment (mrozigor) [inline include/crow/http_response.h:246]: If you don't mind - change this header to `Content-Length` ;)

**Review by mrozigor — APPROVED** [review]
